import pytest

from cybercore.voice.intelligence.safety import SafetyIntentGuard
from cybercore.voice.models import IntentKind, Utterance, VoiceContext


def utterance(text: str) -> Utterance:
    return Utterance(id="u1", session_id="s1", actor_id="johnny", text=text)


@pytest.mark.parametrize(
    "verb",
    [
        "ally",
        "apply",
        "belly",
        "bully",
        "butterfly",
        "colly",
        "comply",
        "dally",
        "dilly-dally",
        "dillydally",
        "fly",
        "imply",
        "jelly",
        "jolly",
        "misally",
        "misapply",
        "multiply",
        "overfly",
        "oversupply",
        "ply",
        "rally",
        "rely",
        "reapply",
        "reply",
        "resupply",
        "sally",
        "shilly-shally",
        "shillyshally",
        "sully",
        "supply",
        "tally",
    ],
)
def test_ly_verbs_preserve_following_cancellation(verb: str) -> None:
    result = SafetyIntentGuard().compile(
        utterance(f"Don't {verb}, stop now"),
        VoiceContext(),
    )
    assert result is not None and result.kind is IntentKind.CANCEL


@pytest.mark.parametrize(
    "text",
    [
        "stop",
        "Please cancel this",
        "zruš to",
        "prosím abort",
        "can you stop now",
        "could you please cancel this",
        "můžeš prosím zrušit to",
        "I need you to stop",
        "hey, stop",
        "Stop!",
        "I would like you to stop",
        "Cyber, stop",
        "Could you maybe stop this now",
        "Don't wait; stop now",
        "Please just stop now",
        "Could you quickly stop now?",
        "Just stop now",
        "Stop the process if it is running",
        "Please, Cyber, stop now",
        "Please don't wait, stop now",
        "Don't, reapply, stop now",
        "Don't, reapply now, stop now",
        "Don't reapply any patch, stop now",
        "Don't, reapply any patch, stop now",
        "Don't, to reapply, stop now",
        "Don't, for resupply, stop now",
        "Don't, with reapply, stop now",
        "Don't, resupply, stop now",
        "Don't, resupply every cache, stop now",
        "Don't, resupply it, stop now",
        "Don't accidentally, stop now",
        "Don't unexpectedly, stop now",
        "If you're still speaking, stop now",
        "When you are done, stop",
        "Stop the process that is running",
        "Stop the process which is running",
        "Stop the process that is running and is noisy",
        "Stop whichever process is running",
        "Stop whoever is speaking",
        "Stop whatever task is running",
        "Stop is a verb, stop now",
        "Stop, which is printed on the button, is a label, stop now",
        "If you're still speaking stop now",
        "When you are done stop",
        "When the process is complete stop",
        "If the session is still active stop now",
        "If you are discussing the incident stop now",
        "If you are explaining the issue stop now",
        "If the service has recovered stop now",
        "If the very long running background process is finally complete stop now",
        "If the service recovers stop now",
        "Unless the process finishes stop now",
        "If the services recover stop now",
        "When we finish stop",
        "Cancel deployment",
        "Stop service now",
        "Stop all services",
        "Abort current deployment",
        "Cancel every job",
        "Don't reply, stop now",
        "Don't apply, stop now",
        "Stop now nothing is working",
        "Cancel now nobody is responding",
        "Stop immediately nothing has changed",
        "Stop now no services are responding",
        "Cancel immediately no workers have replied",
        "Stop the service because it is failing",
        "Cancel this because it is wrong",
        "Stop the service since it is failing",
        "Stop processing immediately please",
        "Cancel deployment right now",
    ],
)
def test_cancel_is_deterministic(text: str) -> None:
    result = SafetyIntentGuard().compile(utterance(text), VoiceContext())
    assert result is not None and result.kind is IntentKind.CANCEL


@pytest.mark.parametrize(
    "text",
    [
        "schvaluju",
        "ano schvaluji plán",
        "jo udělej to",
        "yes do it",
        "Are you ready? Yes, do it.",
        "Připraven? Jo, udělej to.",
        "Please approve this plan",
        "Prosím schvaluji plán",
        "Approve the request that has already been reviewed",
        "Approve the request that will be reviewed",
        "Approve this because it is safe",
    ],
)
def test_approval_is_deterministic(text: str) -> None:
    result = SafetyIntentGuard().compile(utterance(text), VoiceContext())
    assert result is not None and result.kind is IntentKind.APPROVE


@pytest.mark.parametrize(
    "text",
    [
        "execute deploy",
        "spusť kontrolu",
        "proveď změnu",
        "run diagnostics",
        "Run the job that has already been approved",
        "Run the job that will be approved",
        "Run diagnostics because the service is failing",
        "Execute the plan since it is approved",
    ],
)
def test_execute_is_deterministic(text: str) -> None:
    result = SafetyIntentGuard().compile(utterance(text), VoiceContext())
    assert result is not None and result.kind is IntentKind.EXECUTE


@pytest.mark.parametrize(
    "text",
    [
        "What does approve mean?",
        "Explain the word stop",
        "Je run anglicky běžet?",
        "Please do not stop",
        "Don't cancel this",
        "Don't stop; don't cancel",
        'Is "stop" a verb?',
        "Je „stop“ anglické sloveso?",
        "Is stop a verb?",
        "Can I cancel the deployment?",
        "The stop button is red",
        "You should not stop",
        "You must not cancel this",
        "You shouldn't stop",
        "Stop is a verb",
        "Cancel is the operation name",
        "Stop what?",
        "Abort why?",
        "Run what?",
        "Approve what?",
        "Approve nothing",
        "Approve no requests",
        "Approve just nothing",
        "Run nothing",
        "Run simply nowhere",
        "Apply no changes",
        "Approve absolutely nothing",
        "Run the job where?",
        "Stop?",
        "Abort?",
        "Run?",
        "Approve?",
        "Please stop?",
        "Wait. Stop?",
        "Are you sure? Stop?",
        "No. Approve?",
        "Stop please?",
        "Cancel now?",
        "Run please?",
        "Approve now?",
        "Wait, stop?",
        "Wait, please stop?",
        "Cancel the deployment?",
        "Approve this plan?",
        "Run the diagnostics?",
        "Cancel it, actually don't cancel it",
        "Stop the task. Actually, don't stop it",
        "Approve this, actually don't approve it",
        "Run it, actually don't run it",
        "Approve this. Actually, don't approve it.",
        "Run it; actually, don't run it.",
        "Stop failed",
        "Cancel failed",
        "Run failed",
        "Run diagnostics failed",
        "Approve request failed",
        "Stop crashed",
        "Stop broke",
        "Stop froze",
        "Run failed unexpectedly",
        "Run crashed hard",
        "Run hung again",
        "Approve request failed again",
        "Approve request broke",
        "Approve request froze",
        "Yes, do it. Actually, don't do it.",
        "Yes, do it. Actually, don't approve it.",
        "Stop the service why exactly?",
        "Cancel this why please?",
        "Zrušit co?",
        "Zastav proč?",
        "Spusť co?",
        "Schvaluji co?",
        "Zruš nic",
        "Spusť nic",
        "Proveď žádné změny",
        "Zruš nikoho",
        "Schvaluji žádného uživatele",
        "Zruš kterou?",
        "Spusť kterou?",
        "Schvaluji kolik?",
        "Zastav teď?",
        "Spusť teď?",
        "Schvaluji teď?",
        "Počkej, zastav teď?",
        "Yes, do it?",
        "Jo, udělej to?",
        '"yes do it"',
        "'stop'",
        "‘cancel this’",
        "'approve this plan'",
        "‘run diagnostics’",
        "Cancel neither",
        "Cancel nobody",
        "Cancel none",
        "Cancel nothing",
        "Cancel nowhere",
        "Cancel just nothing",
        "Cancel just nothing has changed",
        "Cancel simply nobody",
        "Stop maybe nowhere",
        "Stop button is red",
        "Could you please not stop",
        "Stop this is what the button says",
        "Cancel the deployment is an option",
        "Don't, please, stop",
        "Do not, under any circumstances, stop",
        "Do not, under these circumstances, stop",
        "Do not, without exception, stop",
        "Do not, on any account, stop",
        "Do not, at all costs, stop",
        "Do not, for no reason, stop",
        "Stop which is printed on the button is a label",
        "Cancel that is shown in the menu is a label",
        "Stop which is printed on the button",
        "Stop, which is printed on the button, is a label",
        "Please stop is what the button says",
        "Hey stop is printed on the button",
        "Stop, which means cancel, is a label",
        "If you are saying stop",
        "If you are spelling stop",
        "If you are discussing stop",
        "If you are ready to stop?",
        "If you are mentioning stop",
        "If the session is active can I stop?",
        "If the process is complete we stop automatically",
        "Approve is a verb",
        "Approve means yes",
        "Run is an English verb",
        "Execute is printed on the button",
        "When the show is over applause will stop",
        "When the show is over emergency stop will illuminate",
        "Run diagnostics is printed on the button",
        "Approve the request is printed on the button",
        "If the sign reads stop",
        "Unless the display shows stop",
        "Run diagnostics, which is printed on the button, is a label",
        "Approve the request, which is printed on the button, is a label",
        "When the show is over emergency stop illuminates",
        "When the show is over emergency stop glows",
        "Run diagnostics will be printed on the button",
        "Approve the request will be printed on the button",
        "Run diagnostics has been printed on the button",
        "Approve the request has been printed on the button",
        "When the show is over stop button illuminates",
        "Stop button illuminates",
        "Cancel button glows",
        "If the button is labeled stop",
        "When the operation is named cancel",
        "If the display is showing stop",
        "When the screen is displaying cancel",
        "If the display is showing stop to users",
        "Run diagnostics has already been printed on the button",
        "Approve the request has not been printed on the button",
        "Stop button now illuminates",
        "Cancel message now appears",
        "Don't, please, stop, cancel, or abort",
        "Don't ever, stop, cancel, or abort",
        "Don't ever again, stop",
        "Don't ever accidentally, stop",
        "Don't ever surprisingly, stop",
        "Run diagnostics has already been printed on the button",
        "Approve the request has not been printed on the button",
        "Stop command executes automatically",
        "Cancel message appears",
        "If the display is showing stop",
        "When the screen is displaying cancel",
        "Run diagnostics, which has already been printed on the button, is a label",
        "Approve the request, which has already been reviewed, is a label",
        "Stop command now executes automatically",
        "If the display is presenting stop to users",
        "Run diagnostics, which will be printed on the button, is a label",
        "Approve the request, which will be reviewed, is a label",
        "The buttons say stop, cancel, or abort",
        "The labels are stop, cancel, and abort",
    ],
)
def test_mentions_are_not_authority(text: str) -> None:
    assert SafetyIntentGuard().compile(utterance(text), VoiceContext()) is None
